USE [prbDoubleParners];
GO

IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE [NAME] = 'SP_OBTENER_PERSONAS' AND XTYPE = 'P')
BEGIN
	DROP PROCEDURE SP_OBTENER_PERSONAS
	PRINT '<< DROP PROCEDURE SP_OBTENER_PERSONAS >>'
END
GO

CREATE PROCEDURE SP_OBTENER_PERSONAS
(
	@IDENTIFICADOR INT NULL,
	@TIPOIDENTIFICACION NVARCHAR(3) NULL,
	@NUMEROIDENTIFICACION NVARCHAR(20) NULL,
	@NOMBRES NVARCHAR(50) NULL,
	@APELLIDOS NVARCHAR(50) NULL,
	@EMAIL NVARCHAR(60) NULL,
	@FECHACREACION DATETIME NULL
) 
AS
BEGIN 
	SELECT [Identificador], [TipoIdentificacion], [NumeroIdentificacion], [Nombres], [Apellidos], [Email], 
	       [FechaCreacion], [Identificacion], [NombresApellidos]
	FROM [dbo].[Personas]
	WHERE [Identificador] = COALESCE(@IDENTIFICADOR, [Identificador]) 
	AND [TipoIdentificacion] = COALESCE(@TIPOIDENTIFICACION, [TipoIdentificacion]) 
	AND [NumeroIdentificacion] = COALESCE(@NUMEROIDENTIFICACION, [NumeroIdentificacion]) 
	AND [Nombres] LIKE CASE WHEN @NOMBRES IS NULL THEN [Nombres] ELSE '%' + @NOMBRES + '%' END 
	AND [Apellidos] LIKE CASE WHEN @APELLIDOS IS NULL THEN [Apellidos] ELSE '%' + @APELLIDOS + '%' END 
	AND [Email] = COALESCE(@EMAIL, [Email]) 
	AND [FechaCreacion] = COALESCE(@FECHACREACION, [FechaCreacion]) 
END
GO
IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE [NAME] = 'SP_OBTENER_PERSONAS' AND XTYPE = 'P')
BEGIN
	PRINT '<< CREATE PROCEDURE SP_OBTENER_PERSONAS >>'
END